[package]
name = "terragrunt-dag"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
hcl-rs = "0.18"
rayon = "1.10"
serde = { version = "1", features = ["derive"] }
dashmap = { version = "6", features = [ "rayon" ] }
serde_json = "1"
serde_yaml = "0.9"
camino = { version = "1", features = ["serde1"] }
walkdir = "2"
thiserror = "2"

[dev-dependencies]
rstest = "0.26.1"
tempfile = "3"
